import type { Listing } from "./types";
const entries = [
  [
    "palm-house-galle",
    "The Palm House",
    "Villa",
    "Stay",
    "Galle",
    "Galle",
    "Southern",
    28500,
    "night",
    3,
    3,
    6,
    "villa",
    ["Pool", "Wi-Fi", "Beach access", "Kitchen"],
    "A sun-drenched hideaway, made for slow mornings. An airy tropical villa with a private pool, open living spaces and a peaceful garden. This illustrative listing demonstrates how a property will appear on Ceylon.",
  ],
  [
    "hillside-hideaway-ella",
    "Hillside Hideaway",
    "Cabana",
    "Stay",
    "Ella",
    "Badulla",
    "Uva",
    14500,
    "night",
    1,
    1,
    2,
    "cabin",
    ["Wi-Fi", "Garden", "Parking"],
    "Wake up surrounded by green hills in this cozy timber retreat. Enjoy a quiet terrace, warm interiors and a little room to slow down. This is an illustrative property, not an offer of accommodation.",
  ],
  [
    "ocean-view-residence-colombo",
    "Oceanview Residence",
    "Apartment",
    "Rent",
    "Colombo",
    "Colombo",
    "Western",
    125000,
    "month",
    2,
    2,
    4,
    "apartment",
    ["Air conditioning", "Parking", "Furnished", "Wi-Fi"],
    "A light-filled city apartment with comfortable living spaces and room to make yourself at home. This sample shows the information you can compare for a long-term rental. Availability and pricing are illustrative.",
  ],
  [
    "lake-house-retreat-kandy",
    "The Lake House Retreat",
    "Villa",
    "Stay",
    "Kandy",
    "Kandy",
    "Central",
    22000,
    "night",
    2,
    2,
    4,
    "house",
    ["Garden", "Kitchen", "Parking", "Wi-Fi"],
    "A calm garden retreat for a change of scenery. Spend unhurried afternoons on the terrace and enjoy a comfortable space for your next escape. This is a sample listing for exploring the marketplace.",
  ],
  [
    "coastal-escape-mirissa",
    "A Little Coastal Escape",
    "Hotel",
    "Stay",
    "Mirissa",
    "Matara",
    "Southern",
    18000,
    "night",
    1,
    1,
    2,
    "mirissa-coast",
    ["Beach access", "Air conditioning", "Wi-Fi"],
    "A simple, beautiful base for days by the sea. Discover bright rooms and relaxing corners in this illustrative coastal stay. Contact and booking are disabled for sample properties.",
  ],
  [
    "garden-days-galle",
    "Garden Days",
    "Day out",
    "Day out",
    "Galle",
    "Galle",
    "Southern",
    4500,
    "person",
    0,
    2,
    20,
    "villa",
    ["Pool", "Garden", "Meals included", "Parking"],
    "Make time for a day together, with open gardens and a poolside setting. This sample day package demonstrates a group venue listing. No real booking, capacity or food service is being offered.",
  ],
  [
    "bright-annex-ja-ela",
    "Your Little Garden Annex",
    "Annex",
    "Rent",
    "Ja-Ela",
    "Gampaha",
    "Western",
    35000,
    "month",
    1,
    1,
    2,
    "apartment",
    ["Kitchen", "Parking", "Water"],
    "A bright, self-contained space with a separate entrance, kitchen and room for everyday living. An illustrative annex listing to help you explore rentals around Ja-Ela.",
  ],
  [
    "family-home-kandy",
    "A Home Among the Green",
    "House",
    "Buy",
    "Kandy",
    "Kandy",
    "Central",
    32500000,
    "total",
    4,
    3,
    8,
    "house",
    ["Garden", "Parking", "Kitchen"],
    "An inviting family home with generous spaces and a leafy garden setting. This is a demonstration sale listing; property title, ownership, area and valuation are not represented as verified.",
  ],
] as const;
export const demoListings: Listing[] = entries.map((e, i) => ({
  _id: `demo-${i + 1}`,
  slug: e[0],
  title: e[1],
  category: e[2],
  purpose: e[3],
  city: e[4],
  district: e[5],
  province: e[6],
  area: "",
  price: e[7],
  unit: e[8],
  bedrooms: e[9],
  bathrooms: e[10],
  guests: e[11],
  images: [`/images/${e[12]}.webp`],
  amenities: [...e[13]],
  description: e[14],
  status: "approved",
  featured: i < 4,
  verified: false,
  available: true,
  blockedDates: [],
  contactName: "Ceylon preview",
  contactEmail: "",
  contactPhone: "",
  contactVerified: false,
  createdAt: "2026-09-01T10:00:00.000Z",
  updatedAt: "2026-09-01T10:00:00.000Z",
  history: [],
  demo: true,
  views: 0,
}));
